services:
  sentinel:
    build: .
    container_name: sentinel
    ports:
      - "80:80"
    environment:
      - ROOT_USERNAME=admin
      - ROOT_PASSWORD=admin
    volumes:
      - .docker/sentinel:/db
